version: "3.9"

services:
  weaviate:
    image: semitechnologies/weaviate:${WEAVIATE_VERSION}
    ports:
    - ${WEAVIATE_PORT}:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - wine

  fastapi:
    image: weaviate_wine_fastapi:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${API_PORT}:8000
    depends_on:
      - weaviate
    volumes:
      - ./:/wine
    networks:
      - wine
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  weaviate_data:

networks:
  wine:
    driver: bridge